# -*- coding: utf-8 -*-
"""myname

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ubzEflM7ICE2gGdoiuxOO4EVooDFRU34
"""

print("Ravilla Bhargavi")

